retroroot: wip

diff --git a/make-image b/make-image
--- a/make-image
+++ b/make-image
@@ -2,12 +2,46 @@
 
 set -xe
 
+# global variables
+OUTPUT_IMG=
+LOOP_DEV=
+
+# messages
+die() {
+  printf '\033[1;31mERROR:\033[0m %s\n' "$@" >&2  # bold red
+  exit 1
+}
+
+eerror() {
+  printf '\033[1;31mERROR:\033[0m %s\n' "$@" >&2  # bold red
+}
+
+einfo() {
+  printf '\n\033[1;36m> %s\033[0m\n' "$@" >&2  # bold cyan
+}
+
+ewarn() {
+  printf '\033[1;33m> %s\033[0m\n' "$@" >&2  # bold yellow
+}
+
+# cleanup on exit
+function cleanup {
+  if [ $? -ne 0 ]; then
+    eerror 'something went wrong, exiting...'
+  fi
+  umount -lf /alpine
+  losetup -d "$LOOP_DEV"
+}
+
+# set trap
+trap cleanup EXIT
+
 mkdir -p dist /dist
 
 OUTPUT_IMG="/dist/target.img"
 
 rm -Rf "$OUTPUT_IMG"
-truncate -s 2G "$OUTPUT_IMG"
+truncate -s 512M "$OUTPUT_IMG"
 
 fdisk -H 255 -S 63 "$OUTPUT_IMG" <<-EOF
 o
@@ -31,8 +65,8 @@ BOOT_DEV="$LOOP_DEV"p1
 ROOT_DEV="$LOOP_DEV"p2
 
 # format partitions
-mkfs.fat -F32 -n ALPINE "$BOOT_DEV"
-mkfs.ext4 "$ROOT_DEV"
+mkfs.fat -F32 -n RR-BOOT "$BOOT_DEV"
+mkfs.ext4 -L RR-ROOT "$ROOT_DEV"
 mkdir -p /alpine
 mount --make-private "$ROOT_DEV" /alpine
 mkdir -p /alpine/boot
@@ -44,10 +78,11 @@ BOOT_PARTUUID="${IMGID}-01"
 ROOT_PARTUUID="${IMGID}-02"
 
 apt-get update
-curl https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/master/alpine-chroot-install | sh
+curl https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/master/alpine-chroot-install \
+  | bash -s -- -p ca-certificates -p ssl_client -p busybox-initscripts
 
 cp -R bootstrap/ /alpine/
-/alpine/enter-chroot run-parts /bootstrap/
+/alpine/enter-chroot run-parts --exit-on-error /bootstrap/
 
 rm -rf /alpine/var/lib/apt/lists/*
 rm -rf /alpine/var/cache/apk/*
@@ -57,32 +92,8 @@ rm  /alpine/env.sh /alpine/etc/resolv.conf /alpine/enter-chroot /alpine/destroy
 find /alpine -iname "*-" -delete
 find /alpine -iname "*~" -delete
 
-umount -lf /alpine
-
-# shrink image
-ROOT_PART_START=$(parted -ms "$OUTPUT_IMG" unit B print | tail -n 1 | cut -d ':' -f 2 | tr -d 'B')
-ROOT_BLOCK_SIZE=$(tune2fs -l "$ROOT_DEV" | grep '^Block size:' | tr -d ' ' | cut -d ':' -f 2)
-ROOT_MIN_SIZE=$(resize2fs -P "$ROOT_DEV" | cut -d ':' -f 2 | tr -d ' ')
-
-# shrink fs
-e2fsck -f -p "$ROOT_DEV"
-resize2fs -p "$ROOT_DEV" "$ROOT_MIN_SIZE"
-
-# shrink partition
-PART_END=$((ROOT_PART_START + (ROOT_MIN_SIZE * ROOT_BLOCK_SIZE)))
-parted ---pretend-input-tty "$OUTPUT_IMG" <<EOF
-unit B
-resizepart 2 $PART_END
-yes
-quit
-EOF
-
-losetup -d "$LOOP_DEV"
-
-# truncate free space
-FREE_START=$(parted -ms "$OUTPUT_IMG" unit B print free | tail -1 | cut -d ':' -f 2 | tr -d 'B')
-truncate -s "$FREE_START" "$OUTPUT_IMG"
-
 gzip -c "$OUTPUT_IMG" > "dist/alpine-rpi-$ALPINE_BRANCH-$ARCH.img.gz"
+chmod -R 777 dist
 
-echo "DONE."
+einfo 'DONE.'
+
